### ISSUE TITLE
hi, any accuracy report on common dataset and networks?

### ISSUE THREAD

**Issue by blueardour** [mohdumar644/DoReFaNet-PyTorch#3]
Hi, @mohdumar644 
Exciting to see the implement of dorefa with pytorch. I wonder if you have some accuracy on datasets such as cifar10/100/imagenet and networks of resnet10/20/alexnet to be shared?

Thanks

**Comment by mohdumar644** [comment]
Im sorry I dont. But you can find out for yourself.
